server:
  port: 8080

spring:
  application:
    name: minecraft-k8s-manager
  
  datasource:
    url: jdbc:mysql://basic-tidb.tidb-cluster.svc.cluster.local:4000/gamesmanager?charset=utf8mb4&parseTime=true&serverTimezone=Asia/Shanghai&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456sS#
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

# 端口号配置
minecraft:
  port:
    start: 31003
    end: 32000

# Kubernetes 连接配置
kubernetes:
  kubeconfig:
    base64: "YXBpVmVyc2lvbjogdjEKY2x1c3RlcnM6Ci0gY2x1c3RlcjoKICAgIGNlcnRpZmljYXRlLWF1dGhvcml0eS1kYXRhOiBMUzB0TFMxQ1JVZEpUaUJEUlZKVVNVWkpRMEZVUlMwdExTMHRDazFKU1VKa2VrTkRRVkl5WjBGM1NVSkJaMGxDUVVSQlMwSm5aM0ZvYTJwUFVGRlJSRUZxUVdwTlUwVjNTSGRaUkZaUlVVUkVRbWh5VFROTmRHTXlWbmtLWkcxV2VVeFhUbWhSUkVVelRtcEpNazlFYTNsTlZFMTNTR2hqVGsxcVZYaE5WRUUxVFZSRk1VMTZUWHBYYUdOT1RYcFZlRTFVUVROTlZFVXhUWHBOZWdwWGFrRnFUVk5GZDBoM1dVUldVVkZFUkVKb2NrMHpUWFJqTWxaNVpHMVdlVXhYVG1oUlJFVXpUbXBKTWs5RWEzbE5WRTEzVjFSQlZFSm5ZM0ZvYTJwUENsQlJTVUpDWjJkeGFHdHFUMUJSVFVKQ2QwNURRVUZUVUhWS1lYVm9TV1VyZGpscmNIZEhTVGh5ZWpRNFJYUjRjeXRSYzNab2JFdzRLMlJOTmxCa2VYb0tkRlpCUm1Sc05VOU5WV2hCVUdKM1UxUndXV0oyWkZKUE1rMXNRM2h5VDNBek4wUldkRkFyVlRaMmFWSnZNRWwzVVVSQlQwSm5UbFpJVVRoQ1FXWTRSUXBDUVUxRFFYRlJkMFIzV1VSV1VqQlVRVkZJTDBKQlZYZEJkMFZDTDNwQlpFSm5UbFpJVVRSRlJtZFJWVWhHWm1OS1VYZHRVM1kyUldoMlZrWkhRV2swQ20xSVl6SjRSMDEzUTJkWlNVdHZXa2w2YWpCRlFYZEpSRk5CUVhkU1VVbG5RbXA1VTNOd05WRjJNVTkzY0ZCUVJHRnBaMDh3YW0xb2JqSjBZbUYyVG5nS09DdDFWazFaZDNkSldHdERTVkZEZVd0Q2FIVXhZV05ZYWpSQk5qQXhhVzR5VTNwMk1HUk5iR1ZKUnpSTlNqQkVURE5YYlVGTk5VSmtVVDA5Q2kwdExTMHRSVTVFSUVORlVsUkpSa2xEUVZSRkxTMHRMUzBLCiAgICBzZXJ2ZXI6IGh0dHBzOi8vMTA3LjE0OC40NS4yMDU6NjQ0MwogIG5hbWU6IGRlZmF1bHQKY29udGV4dHM6Ci0gY29udGV4dDoKICAgIGNsdXN0ZXI6IGRlZmF1bHQKICAgIHVzZXI6IGRlZmF1bHQKICBuYW1lOiBkZWZhdWx0CmN1cnJlbnQtY29udGV4dDogZGVmYXVsdApraW5kOiBDb25maWcKcHJlZmVyZW5jZXM6IHt9CnVzZXJzOgotIG5hbWU6IGRlZmF1bHQKICB1c2VyOgogICAgY2xpZW50LWNlcnRpZmljYXRlLWRhdGE6IExTMHRMUzFDUlVkSlRpQkRSVkpVU1VaSlEwRlVSUzB0TFMwdENrMUpTVUpyYWtORFFWUmxaMEYzU1VKQlowbEpZbWhyWVd4Mk1sQkVaVVYzUTJkWlNVdHZXa2w2YWpCRlFYZEpkMGw2UldoTlFqaEhRVEZWUlVGM2Qxa0tZWHBPZWt4WFRuTmhWMVoxWkVNeGFsbFZRWGhPZWxsNVRtcG5OVTFxUlhwTlFqUllSRlJKTVUxVVJYZFBWRVY0VGxSTmVrMHhiMWhFVkVreVRWUkZkd3BQVkVWNFRsUk5lazB4YjNkTlJFVllUVUpWUjBFeFZVVkRhRTFQWXpOc2VtUkhWblJQYlRGb1l6TlNiR051VFhoR1ZFRlVRbWRPVmtKQlRWUkVTRTQxQ21NelVteGlWSEJvV2tjeGNHSnFRbHBOUWsxSFFubHhSMU5OTkRsQlowVkhRME54UjFOTk5EbEJkMFZJUVRCSlFVSkdiMVJtTjNkcWIxVmhXRTlSVFZBS1ZVRXplVU5aWXpBNUx6WnFXWFF4ZERsM2QwUjVTbEV2ZVhreUsxZFhUa3hwTlV4bWJUZEtZMlZPY21wTWRsVjRVM0J2Ym5jdlpFVnBlWEZ3WmxGMVZBcG9Wa2cyUVhCeGFsTkVRa2ROUVRSSFFURlZaRVIzUlVJdmQxRkZRWGRKUm05RVFWUkNaMDVXU0ZOVlJVUkVRVXRDWjJkeVFtZEZSa0pSWTBSQmFrRm1Da0puVGxaSVUwMUZSMFJCVjJkQ1ZHbGxXbkZQUWpWMFlqVk1UWFk1VDJSR1lXVkRXbmhWYWpoUlJFRkxRbWRuY1docmFrOVFVVkZFUVdkT1NrRkVRa2NLUVdsRlFYaEVlalF5WTJKU0swdFVNbmswZERaR2FrWktWVWh5U0dsaGFscE9MMmxQWkc1MWVVUXdZMHRFYkVWRFNWRkVVelZYTWxCUFpXMXNSa1ZzVEFveVNIVXdhbFZxYkhKUFVVRkxaR2xRU1dsRU56QlFNalZJTTJsclQzYzlQUW90TFMwdExVVk9SQ0JEUlZKVVNVWkpRMEZVUlMwdExTMHRDaTB0TFMwdFFrVkhTVTRnUTBWU1ZFbEdTVU5CVkVVdExTMHRMUXBOU1VsQ1pVUkRRMEZTTW1kQmQwbENRV2RKUWtGRVFVdENaMmR4YUd0cVQxQlJVVVJCYWtGcVRWTkZkMGgzV1VSV1VWRkVSRUpvY2swelRYUlpNbmh3Q2xwWE5UQk1WMDVvVVVSRk0wNXFTVEpQUkd0NVRWUk5kMGhvWTA1TmFsVjRUVlJCTlUxVVJURk5lazE2VjJoalRrMTZWWGhOVkVFelRWUkZNVTE2VFhvS1YycEJhazFUUlhkSWQxbEVWbEZSUkVSQ2FISk5NMDEwV1RKNGNGcFhOVEJNVjA1b1VVUkZNMDVxU1RKUFJHdDVUVlJOZDFkVVFWUkNaMk54YUd0cVR3cFFVVWxDUW1kbmNXaHJhazlRVVUxQ1FuZE9RMEZCVWxGRk0xVnpNekEyTkhJd1NHNW5Xa1p2UlZKM1ZIWnJZemd6Ym5oaFUwc3pWbE42Y0ZKc1MxcDNDbE5wY1VacloySmtSVWN4UjBwTmFXNTJkVXRCYWk5T1RtSkdSbXRuWTJJNFVEVnpPRmR0UWxaV1FtUm5iekJKZDFGRVFVOUNaMDVXU0ZFNFFrRm1PRVVLUWtGTlEwRnhVWGRFZDFsRVZsSXdWRUZSU0M5Q1FWVjNRWGRGUWk5NlFXUkNaMDVXU0ZFMFJVWm5VVlUwYm0xaGFtZGxZbGNyVTNwTUwxUnVVbGR1WndwdFkxWkpMMFZCZDBObldVbExiMXBKZW1vd1JVRjNTVVJUVVVGM1VtZEphRUZNZFU1TmIwdDJSVWRrYUZwd2FHWmlVRk4wYzNOeVFuUTJRMnAzY21Ga0NreFhaREUxY0M5eFlXNHJUa0ZwUlVGc2NIaFphVmR0YjBWVmQxTmlVa3BvV1Rsa2FGRjBUbVUxYzFSWFQzcEJUR2w0UlVGWGJtMVVWSEkwUFFvdExTMHRMVVZPUkNCRFJWSlVTVVpKUTBGVVJTMHRMUzB0Q2c9PQogICAgY2xpZW50LWtleS1kYXRhOiBMUzB0TFMxQ1JVZEpUaUJGUXlCUVVrbFdRVlJGSUV0RldTMHRMUzB0Q2sxSVkwTkJVVVZGU1UxU05WVkpaVmNyU210UmIxQkVXbE52VUZJeWVEWjNMelU0U3pWS1IzTlVNVGx4VjNSbVltdzRZWGx2UVc5SFEwTnhSMU5OTkRrS1FYZEZTRzlWVVVSUlowRkZWMmhPTDNaRFQyaFNjR00xUVhjNVVVUm1TVXBvZWxRekwzRk9hVE5YTXpORVFWQkpiRVF2VEV4aU5WcFpNSFZNYTNRcllncHpiSGcwTW5WTmRUbFVSa3R0YVdaRU9UQlRURXR4YkRsRE5VOUdWV1p2UTIxblBUMEtMUzB0TFMxRlRrUWdSVU1nVUZKSlZrRlVSU0JMUlZrdExTMHRMUW89Cg=="

logging:
  level:
    root: INFO
    com.minecraft.k8s: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
